### ISSUE TITLE
Sensor not working

### ISSUE THREAD

**Issue by Zetor77** [ruuvi-friends/ruuvi-hass.io#9]
Hi,

I was trying to setup my Ruuvitag in Hass.io 0.116.2, failed to succeed. I'm getting the following errors at start up:

`
Logger: simple_ruuvitag.decoder
Source: /usr/local/lib/python3.8/site-packages/simple_ruuvitag/decoder.py:28
First occurred: 16.27.45 (16 occurrences)
Last logged: 16.41.13
DATA TYPE 3 IS DEPRECATED - UPDATE YOUR TAG `

`
Logger: bleson
Source: /usr/local/lib/python3.8/site-packages/bleson/core/hci/type_converters.py:193
First occurred: 16.28.46 (19 occurrences)
Last logged: 16.41.13
    TODO: Unhandled GAP type, pos=17 type=0x19 len=3
    TODO: Unhandled GAP type, pos=21 type=0x0a len=2
    TODO: Unhandled GAP type, pos=13 type=0x0a len=2`

`
Logger: bleson
Source: /usr/local/lib/python3.8/site-packages/bleson/core/hci/type_converters.py:194
First occurred: 16.28.46 (19 occurrences)
Last logged: 16.41.13
    Data: 01 00 00 54 52 02 db 2b 58 1a 02 01 06 03 03 0a 18 03 19 00 00 02 0a fe 0b 09 50 41 58 20 43 61 6c 69 6d 61
    Data: 01 00 01 d7 d5 f9 2c 50 4d 11 02 01 1a 02 0a 18 0a ff 4c 00 10 05 09 18 46 71 93
`

`
Logger: bleson
Source: /usr/local/lib/python3.8/site-packages/bleson/core/hci/type_converters.py:195
First occurred: 16.28.46 (19 occurrences)
Last logged: 16.41.13
    POS : 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
    POS : 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
`

`
Logger: bleson
Source: /usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py:271
First occurred: 16.27.44 (166 occurrences)
Last logged: 16.41.14
    TODO: unhandled HCI Event packet, type=HCIPacket(event_name='Command_Status', event_code=15, subevent_code=None, data=b'\x01\x19', length=3)
    TODO: unhandled HCI Event packet, type=HCIPacket(event_name='Command_Status', event_code=15, subevent_code=None, data=b'\x01\x01', length=3)
`

Cheers!

**Comment by sergioisidoro** [comment]
Hi @Zetor77 . Sorry for the delayed reponse.

First thing I see here is that ` DATA TYPE 3 IS DEPRECATED - UPDATE YOUR TAG `
You should update your tag because the type 3 data frame (from older firmwares) might stop working on some platforms. 

Also we have now updated the `bleson` package, so this should be fixed, and the logging be less verbose. Let me know if reinstating the custom component fixes that for you. Remember to _all_ the contents of the `custom_components/ruuvi` folder, as there has been updates to the `manifest.json`
